### ISSUE TITLE
Amazon broke it again...

### ISSUE THREAD

**Issue by sethcohn** [djansen-redhat/KindleCrawler#12]
new category links don't use ref_ ids anymore.

**Comment by djansen-redhat** [comment]
Hi @sethcohn thanks for letting me know. I've patched the crawler with the new locators.
It seems Amazon has implemented a Captcha that obstructs this script - could you let me know if that's a problem for you too?

**Comment by sethcohn** [comment]
Works for me, thanks!  
See my fork for some various improvements I made, just cleaned them up (they were hardcoded before, turned some into arguments).
